# -*- coding: utf-8 -*-
"""Task-2 Main flow services and technologies

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoBHiahVBeaZPrDoh-HDVHITL9MfTGbZ

Task 2
Data manipulation with pandas
Load a CSV file into a Pandas DataFrame. Perform
operations like filtering data based on conditions,
handling missing values, and calculating summary
statistics.

Loading csv file into a pandas dataframe
"""

# we import pandas library to perform data manipulation and analysis
#such as loading data, filtering, handling missing values,calculating statistics.
# Pandas makes working with structured data (like CSV files) much easier and more efficient.
import pandas as pd

#loading data set
df = pd.read_csv('/content/Data Cleaning and Preprocessing.csv')

# head()gives us first top 5 values from the data set
df.head(10)

#tail() gives last 5 values from the dataset
df.tail()

#using info() we get to know the total columns that are present in the data set
#and we get the count of the non null values and the data type
df.info()

"""calculating summary of statistical analysis

"""

# describe() help to get the statistics summary of the dataset
#like count, mean, standard deviation(std), min,max (among the column), quartiles (25%,50%,75%)
df.describe()

"""handling missing values and filtering"""

# here it sums up the total null values counts
df.isnull().sum()

missing_percentage = (151 / (173 + 151)) * 100
print(missing_percentage)

# it gives the count of the non null values
df.count()

#removing the extra spaces from the column names not to get error while performing
df.columns = df.columns.str.strip()
print(df.columns)

#as we dealing with the float kind of data to fill the null values we can use mean or meadian values of that particular column and can
#fill in the null value place
df['SulphidityL4'] = df['SulphidityL4'].fillna(mean_value)

df.head(10)

mean_value2 = df['AAWhiteSt4'].mean()

# Step 3: Fill NaN values in 'ColumnA' with the mean
df['AAWhiteSt4'] = df['AAWhiteSt4'].fillna(mean_value2)

columns_to_fill = [
    'ChipRate', 'BFCMratio', 'BlowFlow', 'ChipLevel4', 'TupperExt2',
    'TlowerExt2', 'UCZAA', 'WhiteFlow4', 'AAWood4', 'ChipMoisture4',
    'SteamFlow4', 'LowerHeatT3', 'UpperHeatT3', 'ChipMass4',
    'WeakLiquorF', 'BlackFlow2', 'WeakWashF', 'SteamHeatF3', 'TTopChips4'
]

# Fill null values with mean for numerical columns
for column in columns_to_fill:
    if df[column].dtype in ['float64', 'int64']:  # Check if the column is numeric
        df[column].fillna(df[column].mean(), inplace=True)

# Display the updated DataFrame
print(df)

# finally there are no null values in the columns they are good for the data analysis
df.isnull().sum()